# Digital Ocean kubernetes cluster config file
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: steel8rat/cache:<TAG> # Dockerhub image name
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: cache
spec:
  type: NodePort
  ports:
    - port: 31997
      targetPort: 8080
      protocol: TCP
  selector:
    app: cache