
name: Test action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Get properties
        id: props
        uses: ./actions/properties

      - name: Check condition
        if: "contains(steps.props.tags, 'scope:server')"
        run: echo "Condition is true"