
name: Test action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get properties
        id: props
        uses: ./github-actions/properties